### ISSUE TITLE
Convert source to JS

### ISSUE THREAD

**Issue by fb55** [pyjs/original-pyjs#731]
I was wondering if it's possible to convert the source code of this project to JS & run it in a JS environment (as that is this project's purpose)? That wouldn't just make using this library a lot easier (as it might be used directly in eg. node, no local Python installation necessary), but could also be used as a testing mechanism: When the compiled code doesn't compile it's source to itself, there must be something wrong.

I'm currently trying to use some Python code in JS, it would be great if I could do that with JS utilities (as I usually don't need to use any Python and barely know the language). A npm package would be great, too (it could directly hook into the `require` function and convert all `.py` files to JS, providing the exported interface).

**Comment by bittner** [comment]
Hi Felix,

if you don't want Python then this project is the wrong place for you. Go and look for pure JavaScript widget libraries, such as jQuery UI or similar. The whole point of this project is provide "JavaScript power" (if you want so) to software developers coding in Python. Python itself is a language that has many advantages over other languages (e.g. JavaScript, Java, PHP, Perl, etc.), the syntax is similar to CoffeeScript. This combination makes the project interesting. For Python lovers.

npm? Pick node.js, CoffeeScript, and a JS widget toolkit of your choice. If you're happy and comfortable with JavaScript stay there! If you'd like to write large projects and keep them maintainable then come back here again.

**Comment by fb55** [comment]
@bittner Isn't one of the goals of this project to convert Python code to JS? That's what I wanted to use it for (I have a python script that I would like to run in the browser). Building interfaces is _one_ usecase of pyjs, but you shouldn't focus solely on it (you can use GWT to write code for node, too).

**Comment by bittner** [comment]
Yes, but not the way you need (and want) it: The purpose of the project is that you can stick with coding Python, i.e. no need to hassle with or even learn JavaScript. The Pyjs compiler then converts your Python code to JavaScript, and you can put the result online (or so). Ideally, as a user, you should never have to look at any of the JavaScript code, neither the one in the project itself nor the one generated by Pyjs.

NOTE: we shouldn't use this bug tracker as a discussion forum. Please join the mailing list if you have more questions! (see http://pyjs.org/#Getting%20Help)

**Comment by anthonyrisinger** [comment]
@FB55, there was work last year during GSoC2011 toward the eventual ability of translating our own source to JS, but we aren't there yet.  it's not so much that something is "wrong" per se, just the simple fact that you _are running in a browser_ (eg. the translator opens files, streams, writes to stdout, etc etc) and not everything has a clear analogue in JS.  the impl of the language itself is almost 100%, save some really tough ones like eval and exec.

the translator is more than capable of converting (mostly) arbitrary Python -> JS, eg. the PureMVC library is 100% usable in JS, but there are restrictions, such as being pure Python and 100% recursive translator support in _all_ libraries/code.

... that said, using the generated code from JS is nothing short of fragile and cumbersome ... remember this is a _compiler_; liken to interfacing with C structures from assembler -- in a meaningful way -- awkward and yuk.  work here, say for an FFI-like interface, is ideas at best.

can you link to the library in question?  the toolkit assumes a more project-oriented approach ATM, but it can be made to work.  please provide additional detail/links; if it seems doable i will re-open the bug and look into your request further.

**Comment by bittner** [comment]
Interestingly, there is a project also called "pyjs" (that has nothing to do with us---hit me if I'm wrong!) that may convert simple Python code to JS, just the way CoffeeScript does: https://github.com/anandology/pyjs -- But is that what you want, Felix?

BTW, found yesterday via https://github.com/jashkenas/coffee-script/wiki/List-of-languages-that-compile-to-JS

P.S.: This was my last response. Please, stop discussing here! Go to the mailing list!

**Comment by fb55** [comment]
@xtfxme Wouldn't it be enough to be able to export functions (directly accessible from JS)? That way, anything related to IO could be separated, so that the compiler-logic can be shipped on it's own.

I want to use existing scripts to convert 3d models to a format usable by [three.js](https://github.com/mrdoob/three.js). As the models that I've got have a usable import script for Blender, I thought of bundeling that with the three.js [exporter](https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender/2.63/scripts/addons/io_mesh_threejs). I have no clue of how practical that is (and if it's even possible), but as I'm mainly writing JS, I would really like to avoid wasting time on learning advanced features of Python, so converting as much code as possible to JS would be a great help (as long as that would be somewhat readable).

@bittner That project doesn't seem to be maintained anymore, and I doubt that it provides all the features I'm going to need.

Thanks for the response(s), anyway.

**Comment by anthonyrisinger** [comment]
@FB55, unfortunately it's not that simple ... while ATM you can indeed call into the compiled code, you must understand impl details to make it safe.  in the future, JS functions may not even _exist_ whatsoever ... my latest prototypes use a switching loop of labels to all-but-eliminate function calls altogether, vastly lowing overhead.  the datatypes in-out are very important as well -- you cannot send simple JS types into compiled functions because they expect objects that fully support python semantics.

if you are merely converting string/primitive formats, and not interacting in a rich, bidirectional manner ... i can probably help you out.  another way is to make the pyjs application write the "output" to a DOM node, notice from JS, read the text, and go from there ... it all depends really ... can you link the the _actual_ scripts you need converted?

however, Peter is correct in closing this (not really a bug), and in his suggestion to take to mailing list. i'm more than happy to explore your request further (but i need the actual python scripts to be translated, along with expected input/output) but it should be on-list so everyone can benefit and learn from the discussion, thanks!

https://groups.google.com/forum/?fromgroups#!forum/pyjs-users
