### ISSUE TITLE
showcase example for ui.Frame does not work

### ISSUE THREAD

**Issue by ghost** [pyjs/original-pyjs#732]
The showcase example for ui.Frame does not work.  You are using google.com was the source, and I believe google is doing something so that its page will now show up in iframes.  When I try pyjs.org that site works.  (maybe change the example to use some other site? Maybe pyjs.org?

**Comment by anthonyrisinger** [comment]
ah nice spotting: http://google.com -> http://www.google.com, but then uses "x-frame-options: SAMEORIGIN" to kill the frame and prevent display.

... anyways, using pyjs.org is a good idea either way; changed! thanks :-)
