### ISSUE TITLE
-j (--static-link) not working

### ISSUE THREAD

**Issue by nathants** [pyjs/original-pyjs#735]
switched to a fresh clone of the new github pyjs.
before i would do " ... -j js/script.js "
now, throws weird errors, tries to find files [ 'j', 's', '/', 's', 'c'... ] instead of "js/script.js"
going back to old pyjamas.git for now :(

**Comment by anthonyrisinger** [comment]
noooo come back :-) when i reworked the options i forgot to add the proper `action` ... appears to work fine now ... lmk if otherwise.

thanks!

**Comment by nathants** [comment]
thanks for the quick fix.
