### ISSUE TITLE
bin directory removed, which causes buildall.sh and build.sh errors

### ISSUE THREAD

**Issue by ghost** [pyjs/original-pyjs#739]
I pulled a copy of the pyjs source code from git, and when I try to build the examples, I receive errors as shown below:

:~/projects/pyjs/examples/raphael$ ./build.sh 
./build.sh: 8: ./build.sh: ../../bin/pyjsbuild: not found
./build.sh: 8: ./build.sh: ../../bin/pyjsbuild: not found
./build.sh: 8: ./build.sh: ../../bin/pyjsbuild: not found
./build.sh: 8: ./build.sh: ../../bin/pyjsbuild: not found
./build.sh: 8: ./build.sh: ../../bin/pyjsbuild: not found

It looks like the bin directory has been removed.  Was this done in error?

Thanks!

**Comment by ghost** [comment]
I've found the error of my ways.  I forgot to run  python bootstrap.py.   Now the bin directory exists! :)

**Comment by anthonyrisinger** [comment]
yeah :-)

bootstrap/hardcoding is really uneccessary; i intend to rewrite this properly, by auto-discovering the environment.
