### ISSUE TITLE
port qwebirc to javascript 

### ISSUE THREAD

**Issue by kanakdeep** [pyjs/original-pyjs#776]
qwebirc from qwebirc.org 

the dependencies are 

python python-twisted python-twisted-bin python-twisted-core python-twisted-runner python-twisted-names python-twisted-mail python-twisted-words python-twisted-web python-zope.interface python-openssl

is it possible to port qwebirc to java script and then can  ....

drupin @ freenode

**Comment by anthonyrisinger** [comment]
please direct such questions at the list.

not impossible i'm sure, but you'd likely need to re-implement huge portions of twisted to make it work, and some parts like TLS/SSL would be pretty much out of the question (possibly via Websocket... possibly)

and the end of the day, you must remember we're still simply running JS -- in a browser -- and everything else is smoke, mirrors, or sugar.
