### ISSUE TITLE
Pyjamas 0.8.1a bug with HTTPRequest

### ISSUE THREAD

**Issue by kveroneau** [pyjs/original-pyjs#791]
Hello,

  For the past few hours I have been struggling with attempting to get a 
simple program to work in Pyjamas 0.8.1a, only to find out that it works in 
0.8 without an issue.  The error being received says: UndefinedValueError

  In order to dive deeper, I needed to edit pyjslib.js and comment out the 
"throw" for this particular error, then I finally received a more helpful 
error:

TypeError: cannot read property 'onProgress' of undefined.

  I looked around but was unable to find a solution, so I thought this same 
routine worked in 0.5 or 0.7(I cannot recall which version I used prior).  
Since these versions are no longer available for download, I decided to try 
out 0.8, and it worked without an issue.  Can you please look into this error 
and see why HTTPRequest isn't working in 0.8.1a?

  Here is the super simple program I was troubleshooting with:

from pyjamas.ui.HTML import HTML
from pyjamas.ui.RootPanel import RootPanel
from pyjamas.HTTPRequest import HTTPRequest

class Callback(HTML):
    def **init**(self):
        HTML.**init**(self, "File will appear here.")
        HTTPRequest().asyncGet("/file.txt", self)
    def onCompletion(self, response):
        self.setHTML(response)

RootPanel().add(Callback())

  I just started a Python server in the output directory using: python -m 
SimpleHTTPServer, so that AJAX requests will be fulfilled correctly.

  This has really delayed a project I am attempting to start...  I will report 
any other errors I may notice during my development.

Best Regards,
  Kevin Veroneau

**Comment by anthonyrisinger** [comment]
have you tried with lateast HEAD? i am preparing for 0.9 release.

**Comment by kveroneau** [comment]
No, I haven't.  I can give it a shot and see if it works.

**Comment by kveroneau** [comment]
It appears to be working with the latest HEAD.

**Comment by anthonyrisinger** [comment]
perfect! another job well done ;)
