### ISSUE TITLE
pyjamas.Canvas.HTML5Canvas

### ISSUE THREAD

**Issue by chris-hawley** [pyjs/original-pyjs#834]
its very long and i can't copy and paste this error but the last part says 
pyjs.translator_pronto.TranslationError: line Unknown: (passes through several modules)

"translator_pronto.TranslationError: pyjamas.Canvas.HTML5Canvas line 5: class method not found: HTML5Canvas.createLinearGradient Function()

None"

**Comment by drevantonder** [comment]
I get this error too.
When I look in the HTML5Canvas.py there is no function createLinearGradient Function().

**Comment by chris-hawley** [comment]
such quick follow up by the devs. i changed to a different library.
